@config
@_book=Deipnosophistae
@author=Athenaeus
@availableStructure=book,chapter
@compiler=Ernst Boogert
@edition=Athenaeus, Deipnosophistae, Georg Kaibel, In Aedibus B.G. Teubneri, Lipsiae, 1887.
@editor=Georg Kaibel
@fmt:text-orig-beta-plain={beta_plain} 
@fmt:text-orig-full={orig} 
@fmt:text-orig-lemma={lemma} 
@fmt:text-orig-main={main} 
@fmt:text-orig-norm={norm} 
@fmt:text-orig-plain={plain} 
@institution=Protestant Theological University (PThU) Amsterdam/Groningen, The Netherlands
@lang=grc
@license=not provided by source
@name=Patristic corpus from Perseus
@purpose=Making Perseus TEI formatted text available in TF
@sectionFeatures=book,chapter,_sentence
@sectionTypes=book,chapter,_sentence
@source1=Perseus Digital Library
@source2=Open Greek and Latin Project
@status=initial unchecked conversion
@structureFeatures=_book,book,chapter,_sentence
@structureTypes=_book,book,chapter,_sentence
@url1=https://github.com/PerseusDL/canonical-greekLit
@url2=https://github.com/OpenGreekAndLatin/First1KGreek
@urn=urn:cts:greekLit:tlg0008.tlg001.perseus-grc3
@valueType=int
@version=1.0
@writtenBy=Text-Fabric
@dateWritten=2019-07-11T10:03:24Z

